apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-service
  name: node-service
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-backend
  type: NodePort
status:
  loadBalancer: {}
