apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-backend
  name: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-backend
    spec:
      containers:
      - image: vidhu830/node-backend:v1
        name: node-backend
        resources: {}
      nodeSelector:
        node-type: worker
status: {}
